config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tasks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  after_create_commit { broadcast_prepend_to "tasks" }
  after_update_commit { broadcast_replace_to "tasks" }
  after_destroy_commit { broadcast_remove_to "tasks" }

  validates :title, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ index show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
    @tasks = Task.all
    respond_to do |format|
      format.turbo_stream { 
        render turbo_stream: turbo_stream.update(
          "task_detail",
          target: 'task_detail', 
          partial: "tasks/detail"
        )
      }
      format.html {
        render :index, status: :ok, location: @task
      }
    end
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@task, partial: "tasks/form", locals: { task: @task}) }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = params[:id].present? ? Task.find(params[:id]) : Task.new
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
    @user = User.new
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :phone_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= turbo_include_tags %>
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="nav flex-column">
  <a class="nav-link active" href="/tasks">Tasks</a>
  <a class="nav-link" href="/users">Users</a>
</nav>

app/views/tasks/_detail.html.erb
<%= @task.title %>
<%= @task.description %>

app/views/tasks/_form.html.erb
<%= simple_form_for task, html: { id: dom_id(task) } do |f| %>
  <%= f.input :title %>
  <%= f.input :description, as: :text %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/tasks/_task.html.erb
<%= turbo_frame_tag dom_id(task) do %>
  <%= link_to task_path(task), data: { controller: "task", task_url_value: task_url(task), action: "click->task#showDetail" } do %>
    <div class="mt-2 border-bottom">
      <h5><%= task.title %></h5>
      <p><%= task.description %></p>
    </div>
  <% end %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="row vh-100">
  <%= turbo_stream_from "tasks" %>
  <p id="notice">
    <%= notice %>
  </p>
  <div class="col-2 border-right">
    Navigation
  </div>
  <div class="col-4 border-right">
    <h5 class="text-muted font-weight-bold">Tasks</h5>  
    <%= turbo_frame_tag "task_form" do %>
      <%= render "tasks/form" , task: Task.new %>
    <% end %>
    <hr />
    <%= turbo_frame_tag "tasks" do %>
      <%= render @tasks %>
    <% end %>
  </div>
  <div class="col-6">
    <%= turbo_frame_tag "task_detail" do %>
      <% if @task.present? && !@task.new_record? %>
        <%= render partial: 'tasks/detail' %>
      <% else %>
        <p>Task details will appear here</p>
      <% end %>  
    <% end %>
  </div>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>
<%= @task.description %>
<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/_detail.html.erb
<%= @user.name %>
<%= @user.email %>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :phone_number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary'  %>
  </div>
<% end %>

app/views/users/_user.html.erb
<%= turbo_frame_tag dom_id(user) do %>
  <%= link_to user_path(user), data: { controller: "user", user_url_value: user_url(user), action: "click->user#showDetail" } do %>
    <div class="mt-2 border-bottom">
      <h5><%= user.name %></h5>
      <p><%= user.email %></p>
      <p><%= user.phone_number %></p>
    </div>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="row vh-100">
  <%= turbo_stream_from "users" %>
  <p id="notice">
    <%= notice %>
  </p>
  <div class="col-2 border-right">
    <%= render partial: 'shared/nav' %>
  </div>
  <div class="col-4 border-right">
    <h5 class="text-muted font-weight-bold">users</h5>  
    <%= turbo_frame_tag "task_form" do %>
      <%= render "users/form" , task: Task.new %>
    <% end %>
    <hr />
    <%= turbo_frame_tag "users" do %>
      <%= render @users %>
    <% end %>
  </div>
  <div class="col-6">
    <%= turbo_frame_tag "task_detail" do %>
      <% if @task.present? && !@task.new_record? %>
        <%= render partial: 'users/detail' %>
      <% else %>
        <p>User details will appear here</p>
      <% end %>  
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @user.phone_number %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>